const currencySymbols = {
    AED: "&#x62F;&#x2E;&#x625;", // د.إ
    AFN: "&#x60B;", // ؋
    ALL: "L", // L
    AMD: "&#x584;", // ֏
    ANG: "&#x192;", // ƒ
    AOA: "Kz", // Kz
    ARS: "&#x24;", // $
    AUD: "&#x24;", // $
    AWG: "&#x192;", // ƒ
    AZN: "&#x20BC;", // ₼
    BAM: "KM", // KM
    BBD: "&#x24;", // $
    BDT: "&#2547;", // ৳
    BGN: "&#x43B;&#x432;", // лв
    BHD: "&#x62F;&#x2E;&#x628;", // د.ب
    BIF: "FBu", // FBu
    BMD: "&#x24;", // $
    BND: "&#x24;", // $
    BOB: "Bs.", // Bs.
    BRL: "R&#x24;", // R$
    BSD: "&#x24;", // $
    BTN: "&#x20B9;", // ₹
    BWP: "P", // P
    BYN: "Br", // Br
    BZD: "BZ&#x24;", // BZ$
    CAD: "&#x24;", // $
    CDF: "FC", // FC
    CHF: "CHF", // CHF
    CLP: "&#x24;", // $
    CNY: "&#xA5;", // ¥
    COP: "&#x24;", // $
    CRC: "&#x20A1;", // ₡
    CUP: "&#x20B1;", // ₱
    CVE: "&#x24;", // $
    CZK: "K&#x10D;", // Kč
    DJF: "Fdj", // Fdj
    DKK: "kr", // kr
    DOP: "RD&#x24;", // RD$
    DZD: "&#x62F;&#x2E;&#x62C;", // د.ج
    EGP: "&#xA3;", // £
    ERN: "Nfk", // Nfk
    ETB: "Br", // Br
    EUR: "&#x20AC;", // €
    FJD: "&#x24;", // $
    FKP: "&#xA3;", // £
    GBP: "&#xA3;", // £
    GEL: "&#x20BE;", // ₾
    GHS: "&#x20B5;", // ₵
    GIP: "&#xA3;", // £
    GMD: "D", // D
    GNF: "FG", // FG
    GTQ: "Q", // Q
    GYD: "&#x24;", // $
    HKD: "&#x24;", // $
    HNL: "L", // L
    HRK: "kn", // kn
    HTG: "G", // G
    HUF: "Ft", // Ft
    IDR: "Rp", // Rp
    ILS: "&#x20AA;", // ₪
    INR: "&#x20B9;", // ₹
    IQD: "&#x62F;&#x2E;&#x639;", // د.ع
    IRR: "&#xFDFC;", // ﷼
    ISK: "kr", // kr
    JMD: "J&#x24;", // J$
    JOD: "&#x62F;&#x2E;&#x627;", // د.ا
    JPY: "&#xA5;", // ¥
    KES: "KSh", // KSh
    KGS: "&#x43B;&#x432;", // лв
    KHR: "&#x17DB;", // ៛
    KMF: "CF", // CF
    KRW: "&#x20A9;", // ₩
    KWD: "&#x62F;&#x2E;&#x643;", // د.ك
    KZT: "&#x20B8;", // ₸
    LAK: "&#x20AD;", // ₭
    LBP: "&#xA3;", // £
    LKR: "&#x20A8;", // ₨
    LRD: "&#x24;", // $
    LSL: "L", // L
    LYD: "&#x62F;&#x2E;&#x644;", // د.ل
    MAD: "&#x62F;&#x2E;&#x645;", // د.م
    MDL: "L", // L
    MGA: "Ar", // Ar
    MKD: "&#x434;&#x435;&#x43D;", // ден
    MMK: "K", // K
    MNT: "&#x20AE;", // ₮
    MOP: "MOP&#x24;", // MOP$
    MRU: "UM", // UM
    MUR: "&#x20A8;", // ₨
    MVR: "Rf", // Rf
    MWK: "MK", // MK
    MXN: "&#x24;", // $
    MYR: "RM", // RM
    MZN: "MT", // MT
    NAD: "&#x24;", // $
    NGN: "&#x20A6;", // ₦
    NIO: "C&#x24;", // C$
    NOK: "kr", // kr
    NPR: "&#x20A8;", // ₨
    NZD: "&#x24;", // $
    OMR: "&#xFDFC;", // ﷼
    PAB: "B/.", // B/.
    PEN: "S/", // S/
    PGK: "K", // K
    PHP: "&#x20B1;", // ₱
    PKR: "&#x20A8;", // ₨
    PLN: "z&#x142;", // zł
    PYG: "&#x20B2;", // ₲
    QAR: "&#xFDFC;", // ﷼
    RON: "lei", // lei
    RSD: "din", // din
    RUB: "&#x20BD;", // ₽
    RWF: "FRw", // FRw
    SAR: "&#xFDFC;", // ﷼
    SBD: "&#x24;", // $
    SCR: "&#x20A8;", // ₨
    SDG: "&#x62C;&#x2E;&#x633;", // ج.س
    SEK: "kr", // kr
    SGD: "&#x24;", // $
    SHP: "&#xA3;", // £
    SLL: "Le", // Le
    SOS: "Sh", // Sh
    SRD: "&#x24;", // $
    SSP: "&#xA3;", // £
    STN: "Db", // Db
    SYP: "&#xA3;", // £
    SZL: "L", // L
    THB: "&#xE3F;", // ฿
    TJS: "SM", // SM
    TMT: "m", // m
    TND: "&#x62F;&#x2E;&#x62A;", // د.ت
    TOP: "T&#x24;", // T$
    TRY: "&#x20BA;", // ₺
    TTD: "TT&#x24;", // TT$
    TWD: "NT&#x24;", // NT$
    TZS: "Sh", // Sh
    UAH: "&#x20B4;", // ₴
    UGX: "USh", // USh
    USD: "&#x24;", // $
    UYU: "&#x24;U", // $U
    UZS: "so&#x2BB;m", // soʻm
    VES: "Bs.", // Bs.
    VND: "&#x20AB;", // ₫
    VUV: "Vt", // Vt
    WST: "T", // T
    XAF: "FCFA", // FCFA
    XCD: "&#x24;", // $
    XOF: "CFA", // CFA
    XPF: "&#x20A3;", // ₣
    YER: "&#xFDFC;", // ﷼
    ZAR: "R", // R
    ZMW: "ZK", // ZK
    ZWL: "Z&#x24;", // Z$
};
